// Generated by CoffeeScript 1.6.3
/*

  http://bl.ocks.org/mbostock/4063550
*/


(function() {
  var EdgeChooser;

  EdgeChooser = (function() {
    function EdgeChooser() {}

    return EdgeChooser;

  })();

  window.EdgeChooser = EdgeChooser;

}).call(this);
