variables:
  # ROLLOUT_RESOURCE_TYPE: deployment
  CODE_QUALITY_DISABLED: 1
#  CONTAINER_SCANNING_DISABLED: 1
#  DEPENDENCY_SCANNING_DISABLED: 1
#  LICENSE_MANAGEMENT_DISABLED: 1
  SAST_DISABLED: 1
  SECRET_DETECTION_DISABLED: 1
  TEST_DISABLED: 1
  DAST_DISABLED: 1
  PERFORMANCE_DISABLED: 1
  REVIEW_DISABLED: 1
  POSTGRES_ENABLED: "false"
  STAGING_ENABLED: 1
  K8S_SECRET_PORT: 5000
  PORT: 5000

include:
  - template: Auto-DevOps.gitlab-ci.yml

# override some of the deploy parameters
staging:
  stage: deploy
  environment:
    name: staging
    url: https://huviz.$KUBE_INGRESS_BASE_DOMAIN

production_manual:
  stage: deploy
  environment:
    name: production
    url: https://huviz.$KUBE_INGRESS_BASE_DOMAIN
