# Use Auto DevOps pipeline
# https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Auto-DevOps.gitlab-ci.yml
include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  # GitLab CI configuration
  BROWSER_PERFORMANCE_DISABLED: 1
  CODE_QUALITY_DISABLED: 1
#  CONTAINER_SCANNING_DISABLED: 1
  DEPENDENCY_SCANNING_DISABLED: 1
#  LICENSE_MANAGEMENT_DISABLED: 1
  DISABLE_LICENSE_SCANNING: 1
  SAST_DISABLED: 1
  SECRET_DETECTION_DISABLED: 1
  DAST_DISABLED: 1
  PERFORMANCE_DISABLED: 1
  POSTGRES_ENABLED: "false"
  STAGING_ENABLED: 1

  # HuViz container variables
  K8S_SECRET_PORT: 5000

  KUBE_INGRESS_BASE_DOMAIN: dev.lincsproject.ca
  KUBE_CONTEXT: "calincs/gitlab-agents:dev-agent"
  KUBE_NAMESPACE: "huviz"    


# Override test job
test:
  needs:
    - build
  image: node:14
  script:
    - npm install
    - npm run test:unit
  needs:
    - build

# Only rebuild node_modules if package.json changes
cache:
  key:
    files:
      - package.json
  paths:
    - node_modules

# Template to override common deployment parameters
.deployment: &deployment
  environment:
    url: http://huviz.$KUBE_INGRESS_BASE_DOMAIN

# override some staging parameters
staging:
  <<: *deployment
  variables:
    KUBE_INGRESS_BASE_DOMAIN: stage.lincsproject.ca
    KUBE_CONTEXT: "calincs/gitlab-agents:stage-agent"
    KUBE_NAMESPACE: "huviz"

# override some production parameters
production_manual:
  <<: *deployment
  variables:
    KUBE_INGRESS_BASE_DOMAIN: lincsproject.ca
    KUBE_CONTEXT: "calincs/gitlab-agents:prod-agent"
    KUBE_NAMESPACE: "huviz"

